### PR TITLE
support switch iconTheme

### LINKED ISSUE #25: [Request] Also switch icon theme
This extension is awesome.

But I have such a problem, I use `Catppuccin.catppuccin-vsc-icons` extension, it has light and dark icon styles, so when the theme of vscode is switched to light (Solarized Light), it should be in light The theme uses a dark icon style, but at this time it is still a light icon style ("workbench.iconTheme": "catppuccin-mocha"), which makes it difficult to distinguish the icon.

So my request is, please to be able to switch the icon style at the same time.

Current:
 - left
    - theme: Default Dark Modern
    - icon:  catppuccin-mocha
 - right
	- theme: Solarized Light
    - icon:  catppuccin-mocha

theme: Default Dark Modern | theme: Solarized Light
---|---

Expect:
 - left
    - theme: Default Dark Modern
    - icon:  catppuccin-mocha
 - right
	- theme: Solarized Light
    - icon:  catppuccin-latte  // changed

theme: Default Dark Modern | theme: Solarized Light
---|---

### PR DESCRIPTION
**Pull request by zzhaolei**
Close #25

### CODE REVIEW

**Comment by savioserra** [comment]
Hey @zzhaolei, thank you very much for this pull request! The only thing that stands out to me is that we should check if `iconTheme` is `undefined` before making that change, so we don’t have to always specify icon themes.

**Comment by zzhaolei** [comment]
> The only thing that stands out to me is that we should check if `iconTheme` is `undefined` before making that change, so we don’t have to always specify icon themes. I can make this change if you want. :)

Of course, I updated the code. If iconTheme is not set, now behaves the same as before.

**Comment by zzhaolei** [comment]
Hey, Can you merge this? @savioserra

**Comment by zzhaolei** [comment]
friendly ping @savioserra

**Comment by zzhaolei** [comment]
Hello, can you merge this PR, please?

**Pull request closed without merging**
